<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PlatformTarget>x64</PlatformTarget>
		<UseWPF>true</UseWPF>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Clipper2" Version="2.0.0" />
		<PackageReference Include="EPPlus" Version="8.6.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\GeoAppCore\GeoAppCore.csproj" />
	</ItemGroup>


	<ItemGroup>
		<Reference Include="accoremgd">
			<HintPath>dlls\accoremgd.dll</HintPath>
		</Reference>
		<Reference Include="Acdbmgd">
			<HintPath>dlls\acdbmgd.dll</HintPath>
		</Reference>
		<Reference Include="Acmgd">
			<HintPath>dlls\acmgd.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
