<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GeoAppCore\GeoAppCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="accoremgd">
      <HintPath>E:\Program Files\ACAD23\dlls\accoremgd.dll</HintPath>
    </Reference>
    <Reference Include="Acdbmgd">
      <HintPath>E:\Program Files\ACAD23\dlls\acdbmgd.dll</HintPath>
    </Reference>
    <Reference Include="Acmgd">
      <HintPath>E:\Program Files\ACAD23\dlls\acmgd.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
