<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HelixToolkit.Wpf" Version="3.1.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GeoAppCore\GeoAppCore.csproj" />
    <ProjectReference Include="..\GeoCad.Infrastructure\GeoCad.Infrastructure.csproj" />
    <ProjectReference Include="..\LegendDesignWpf\LegendDesignWpf.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Controls\ObjectTreeControl.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Controls\QuickPanelControl.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
