<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<UseWPF>true</UseWPF>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Styles\UserControlStyles.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\CustomPage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\ExpandableSettingItem.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\PackIcon.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\PopupItem.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\SearchBox.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\SettingItem.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\Switch.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
